/** From DOC/stitch_bazar_ciro_crisis_system/.../DESIGN.md */
export const THEME = {
  background: '#FAF8FF',
  surface: '#FFFFFF',
  surfaceDim: '#F2F3FF',
  surfaceContainer: '#EAEDFF',
  onSurface: '#161B2A',
  onSurfaceVariant: '#3F4943',
  outline: '#E2E6EA',
  outlineVariant: '#BEC9C1',
  primary: '#005539',
  primaryContainer: '#1D6E4E',
  onPrimary: '#FFFFFF',
  secondary: '#006C4E',
  tertiary: '#4238A5',
  error: '#BA1A1A',
  errorContainer: '#FCEBEB',
  fair: '#1D9E75',
  warning: '#BA7517',
  gouging: '#E24B4A',
  agentCiro: '#4238A5',
  agentSupply: '#006C4E',
  agentTruth: '#1D6E4E',
  radiusCard: 14,
  radiusBtn: 8,
};
